### ISSUE TITLE
[Bug Report] Button icon sync

### ISSUE THREAD

**Issue by GoGiants1** [ColaboAI/ColaboAI-web_v1#8]
하단 재생바 재생, 일시정지 버튼 누르면 메인 목록에서 재생 버튼과 싱크가 맞지 않음.

**Comment by sgeunhi** [comment]
확인했습니다. 수정한 후 코멘트 남기겠습니다.

**Comment by GoGiants1** [comment]
버튼에 마우스 포인터 올릴 때, 클릭 가능하다는 느낌의 포인터로 변경해주는게 좋겠습니다.

**Comment by sgeunhi** [comment]
수정 완료
